/*Catálogo de fallas*/
INSERT INTO fallas(nombre) VALUES
('No enciende'),
('Se apaga'),
('No inicia el SO'),
('Reparación externa'),
('Teclado mojado'),
('Mal funcionamiento'),
('Sensor óptico dañado'),
('Falla de botón izquierdo'),
('Falla de botón derecho.'),
('Falla de scroll.'),
('Cambio de batería'),
('Reparación Externa'),
('Cable de video VGA.'),
('Cable de video DVI.'),
('Cable de video HDMI'),
('Reparación externa'),
('No imprime'),
('Error de impresión'),
('Atasco de papel'),
('Machas o líneas en hojas '),
('Cambio de combustibles'),
('Reparación Interna '),
('Reparación externa'),
('No imprime'),
('Error en impresión'),
('Atasco de papel'),
('Impresiones con caracteres'),
('Manchas o líneas en las hojas'),
('Cambio de consumibles'),
('Reporte con proveedor'),
('Internet lento'),
('Sin acceso a sistemas externos'),
('Sin acceso a sistemas internos'),
('Sin Internet'),
('Alta/Baja de dirección IP/MAC'),
('Instalación de software libre'),
('Restauración de fábrica'),
('Impresión'),
('Copiado'),
('Escaneo '),
('Software'),
('Email'),
('Telefonía'),
('Navegación en Internet'),
('Impresión'),
('Copiado'),
('Escaneo '),
('Software'),
('Email'),
('Telefonía'),
('Navegación en Internet'),
('Grabar información'),
('Reubicación'),
('Préstamo de CPU'),
('Préstamo de Monitor'),
('Préstamo de Mouse'),
('Préstamo de Teclado'),
('Reasignación de CPU'),
('Reasignación de Monitor'),
('Reasignación de Mouse'),
('Reasignación de Teclado'),
('Alta'),
('Baja'),
('Modificación'),
('Alta'),
('Baja'),
('Modificación'),
('Instalación'),
('Desinstalación'),
('Cambio'),
('Escaneo'),
('Desinfección');