INSERT INTO rubros (nombre) VALUES
('APOYO ESCANEOS'),
('EMAIL'),
('GRABAR INFORMACIÓN'),
('RED LOCAL'),
('SOFTWARE'),
('COMPUTADORA'),
('TELEFONÍA'),
('VIRUS Y MALWARE'),
('WINDOWS'),
('NOBREAK'),
('COPIADORAS'),
('IMPRESORAS');
